### ISSUE TITLE
Question: Is it intended that `target` can only be arrays?

### ISSUE THREAD

**Issue by GlennGeelen** [yowainwright/reframe.js#149]
## Examples
So we used to have `reframe(document.querySelector("iframe"))` and this worked fine, but since the new update this does not work. We're getting the following error:
```
reframe.es.js:26 Uncaught RangeError: Invalid array length
    at __spreadArrays (reframe.es.js:26)
    at reframe (reframe.es.js:42)
    ...
```

If I look at the error line I see the reframe `target` is no longer converted to an array. Instead it assumes the `target` is already an array.

This means we can change our code to:
- `reframe([document.querySelector("iframe")])` 
- `reframe(document.querySelectorAll("iframe"))`
- `reframe("iframe")`

**But is this expected behaviour, or do still want to allow the target to be a single object as well?**

**Comment by GlennGeelen** [comment]
Also if this was intentional the following line in the readme does not work either:
https://github.com/yowainwright/reframe.js/blame/master/README.md#L67

**Comment by yowainwright** [comment]
It wasn't intentional. Care to submit a pull request @GlennGeelen ?

**Comment by GlennGeelen** [comment]
@yowainwright Sorry for the late response, but I'll make a pull request.
